[package]
name = "sl21-co2"
version = "0.1.0"
authors = ["mikelma <mikelma7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.12.0"
slice-deque = "0.3.0"
json = "0.12.4"
